ALTER TABLE users ADD COLUMN phone VARCHAR(20);
ALTER TABLE users ADD COLUMN cpf VARCHAR(14) UNIQUE;
ALTER TABLE users ADD COLUMN birth_date VARCHAR(10);
ALTER TABLE users ADD COLUMN cro VARCHAR(20);
ALTER TABLE users ADD COLUMN cro_state VARCHAR(2);
ALTER TABLE users ADD COLUMN specialty TEXT;
ALTER TABLE users ADD COLUMN clinic_id UUID REFERENCES clinics(id);